### ISSUE TITLE
Reading from "node:fs" is not handled by plugins (Unhandled scheme).

### ISSUE THREAD

**Issue by jsinglet** [kevin940726/remark-code-import#22]
I was attempting to use this plugin with Next.js 12.0.7 -- however, when I add it I get the following error:

```
[dev:*next] Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).
[dev:*next] Webpack supports "data:" and "file:" URIs by default.
[dev:*next] You may need an additional plugin to handle "node:" URIs.
```

This is of course coming from this:

```
import fs from 'node:fs';
import path from 'node:path';
import { EOL } from 'node:os';
import { visit } from 'unist-util-visit';
import stripIndent from 'strip-indent';
```

I spent a bunch of time trying various solutions with webpack and next -- I see that there is some incompatibility with various versions of webpack and next however I am unable to find a solution. 

Filing this here but I would appreciate any insight into getting this plugin working!

**Comment by kevin940726** [comment]
The `node:` scheme is a nodejs [standard](https://nodejs.org/api/esm.html#node-imports) and is supported (backported) all the way down to v12.

Possible related issues for:
- Next.js (https://github.com/vercel/next.js/issues/28774)
- webpack (https://github.com/webpack/webpack/issues/13290)

I see that this is still an issue in Next.js. Maybe you can try [one](https://github.com/vercel/next.js/issues/28774#issuecomment-1208649870) of the solutions/workarounds provided in the thread? LMK if it helps 😉.

**Comment by jsinglet** [comment]
Thanks for the quick response @kevin940726! Sadly, I've tried like every variation of the solutions (and hacks) in those threads with no luck :( Maybe I'm doing something wrong but I even tried the "delete the .next directory" one. Any ideas?

**Comment by jsinglet** [comment]
Going to close this. I was able to get this working by adapting the plugin code to fit my usecase -- passing in a handle to the fs module is essentially what I had to do. It won't work in general so I don't have anything to contribute back to your plugin.
