### ISSUE TITLE
Export an ESM default to support remark-cli

### ISSUE THREAD

**Issue by djmcgreal-cc** [kevin940726/remark-code-import#26]
Hi,

I'm unable to run the plugin through `remark-cli`.

> Error: Expected a plugin or preset exported as the default export

See: https://github.com/remarkjs/remark/blob/main/doc/plugins.md#create-plugins, https://github.com/remarkjs/remark/issues/654#issuecomment-1532846049

**Comment by kevin940726** [comment]
Good idea! I'll try to find some time to do this. PR welcome too!

**Comment by djmcgreal-cc** [comment]
I'd love to be able to help but I don't know enough about it I'm afraid. Thanks in advance if you're able to make the addition though!

**Comment by kevin940726** [comment]
There should now be a default export in the latest version `v1.2.0`. Please try it out and LMK if it works for you :).

**Comment by djmcgreal-cc** [comment]
It works, thank you kindly.
